# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenTAKServer Documentation
theme:
  name: null
  custom_dir: windmill
  search_index_only: true
  include_search_page: true
plugins:
  - glightbox
  - search
extra:
  version: 1.4.1
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: false
  gtag: 'G-22JB0TDCSP'
  discord_link: https://discord.gg/6uaVHjtfXN
repo_url: https://github.com/brian7704/OpenTAKServer
site_url: https://docs.opentakserver.io
edit_uri: https://github.com/brian7704/OpenTAKServer-docs/tree/master/docs
nav:
  - Home: 'main_old.md'
  - Architecture: 'architecture.md'
  - Feature Comparison: 'feature_comparison.md'
  - Installation:
    - Installer: 'installation/installation.md'
    - Windows: 'installation/windows.md'
    - macOS: 'installation/macOS.md'
    - Upgrading: 'installation/upgrading.md'
  - Configuration: 'configuration.md'
  - Let's Encrypt: 'lets_encrypt.md'
  - Data Packages: 'data_packages.md'
  - Security: 'security.md'
  - Database: 'database.md'
  - CoT Routing: 'cot_routing.md'
  - Certificate Enrollment: 'certificate_enrollment.md'
  - Mission API/Data Sync: 'mission_api.md'
  - Email: 'email.md'
  - Authentication: 'authentication.md'
  - API: 'API_old.md'
  - ADS-B: 'adsb.md'
  - AIS: 'ais.md'
  - Deleting Old Data: 'delete_old_data.md'
  - Device Profiles: 'device_profiles.md'
  - Plugin Update Server: 'update_server.md'
  - CloudTAK: 'cloudtak.md'
  - Mumble: 'mumble.md'
  - Symbology: 'symbology.md'
  - Video Streaming: 'video_streaming.md'
  - Meshtastic: 'meshtastic.md'
  - TAK Meshtastic Gateway: 'tak_meshtastic_gateway.md'
  - Public Server: 'public_server.md'
  - OpenTAK ICU:
    - OpenTAK ICU: 'opentak_icu/main_old.md'
    - UVC Cameras: 'opentak_icu/uvc_cameras.md'
    - Streaming Protocols: 'opentak_icu/streaming_protocols.md'
    - Audio Codecs: 'opentak_icu/audio_codecs.md'
    - Video Codecs: 'opentak_icu/video_codecs.md'
    - Recording: 'opentak_icu/recording.md'
    - Encryption: 'opentak_icu/encryption.md'
    - Video Filters: 'opentak_icu/video_filters.md'
    - IR Cameras: 'opentak_icu/ir_cameras.md'
    - TAK Server: 'opentak_icu/tak_server.md'
    - MediaMTX: 'opentak_icu/mediamtx.md'